export const links = {
    base: "/",
    hotelcatalog: "hotelcatalog",
    "personal-area": "personal-area",
    about: "about",
    register: "register",
    confirmCode: "confirmCode",
    auth: "auth",
    businessMainPage: "businessMainPage",
    businessAccountData: "businessAccountData",
    fillingHotelDetails: "fillingHotelDetails",
    fillingRoomDetails: "fillingRoomDetails",
    businessOwnerNotification: "businessOwnerNotification",
    support: "support",
    test: "test",
    restorePassEmail: "restorePassEmail",
    restorePassCode: "restorePassCode",
    restorePassNewPass: "restorePassNewPass",
    favorites: "favorites",
}